apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository-grafana.yaml
  - helmrepository-grafana-community.yaml
  - loki.yaml
  - promtail.yaml
  - grafana.yaml
