USER-SUPPLIED VALUES:
backend:
  replicas: 0
deploymentMode: SingleBinary
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  useTestSchema: true
read:
  replicas: 0
singleBinary:
  replicas: 1
write:
  replicas: 0
